Repository Automattic/gridicons, pull requests merged in 2018-03, with the labels that each got.

#285 Add Multiple Users Icon
  docs/gridicons.svg
  docs/index.html
  package-lock.json
  package.json
  pdf/gridicons-multiple-users.pdf
  php/gridicons.php
  sources/svg/gridicons-multiple-users.svg
  svg-min/gridicons-multiple-users.svg
  svg-sprite/gridicons.svg
  svg-sprite/index.html
Labels: [Status] Ready to Merge, enhancement

#287 Ignore package-lock.json
  .gitignore
  package-lock.json
Labels: [Status] Needs Review, build

#283 Allow Gridicons library to be imported by component
  .gitignore
  CHANGELOG.md
  Gruntfile.js
  README.md
  grunt-tasks/svg-to-react.js
  package.json
  sources/react/example-footer.jsx
  sources/react/icons-offset.js
  sources/react/index-footer.jsx
  sources/react/index-header.jsx
  sources/react/template-all-icons.js
  sources/react/template-devdocs-example.js
  sources/react/template-individual-icon.js
Labels: [Status] Needs Review, build

#289 Fix/main gridicon component
  CHANGELOG.md
  package.json
  sources/react/template-all-icons.js
Labels: [Status] Needs Review
